version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: Portainer
    ports:
      - 9443:9443
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: Uptime-Kuma
    ports:
      - 3001:3001
    volumes:
      - ./uptime-kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always